IF OBJECT_ID('tempdb.dbo.#sp_Who2')   IS NOT NULL DROP TABLE #sp_Who2;

CREATE TABLE #sp_Who2
(
	SPID INT, STATUS VARCHAR(1000) NULL, LOGIN SYSNAME NULL, HostName SYSNAME NULL, BlkBy SYSNAME NULL, DBName SYSNAME NULL, Command VARCHAR(1000) NULL, CPUTime INT NULL, DiskIO BIGINT NULL, -- int
	LastBatch VARCHAR(1000) NULL, ProgramName VARCHAR(1000) NULL, SPID2 INT, RequestId INT NULL --comment out for SQL 2000 databases
)
INSERT INTO #sp_Who2 EXEC sp_who2;
SELECT * FROM #sp_Who2 WHERE DBName = 'yourDb'